name: Go

on:
#   push:
#     paths:
#     - 'go/**'
#     - 'deployments/**'
#     branches:
#     - '**'
  pull_request:
    paths:
    - 'go/**'
    - 'deployments/**'
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./go
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - run: go version
    - name: Go test
      run: go test ./...
